ALTER TABLE DEDUP_DECISION ADD COLUMN EXECUTION_TOKEN varchar NULL;
ALTER TABLE DEDUP_DECISION ADD COLUMN LEASE_UNTIL datetime NULL;
ALTER TABLE DEDUP_DECISION ADD COLUMN RESULT_JSON varchar NOT NULL DEFAULT '{}';
ALTER TABLE DEDUP_DECISION ADD COLUMN GORSE_SYNC_STATE varchar NOT NULL DEFAULT 'PENDING';
ALTER TABLE DEDUP_DECISION ADD COLUMN REMOTE_CONFIRMATION_STATE varchar NOT NULL DEFAULT 'UNKNOWN';

ALTER TABLE DEDUP_DECISION_ITEM ADD COLUMN STATE_REVISION varchar NOT NULL DEFAULT '';
ALTER TABLE DEDUP_DECISION_ITEM ADD COLUMN ACKNOWLEDGED_REASONS_JSON varchar NOT NULL DEFAULT '[]';
ALTER TABLE DEDUP_DECISION_ITEM ADD COLUMN STABILITY_NOT_BEFORE datetime NULL;
ALTER TABLE DEDUP_DECISION_ITEM ADD COLUMN DELETED_DATE datetime NULL;

CREATE INDEX IDX__DEDUP_DECISION__LEASE
    ON DEDUP_DECISION (STATE, LEASE_UNTIL);

CREATE TABLE DEDUP_GORSE_SYNC
(
    SERIES_ID           varchar  NOT NULL PRIMARY KEY,
    LIBRARY_ID          varchar  NOT NULL,
    DESIRED_HIDDEN      boolean  NOT NULL,
    STATE               varchar  NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT       integer  NOT NULL DEFAULT 0,
    NEXT_RETRY_AT       datetime NULL,
    LAST_ERROR          varchar  NULL,
    CREATED_DATE        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_DATE      datetime NULL,
    CHECK (STATE IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED_REVIEW'))
);

CREATE INDEX IDX__DEDUP_GORSE_SYNC__CLAIM
    ON DEDUP_GORSE_SYNC (STATE, NEXT_RETRY_AT, LAST_MODIFIED_DATE);
