DROP TABLE IF EXISTS DEDUP_GORSE_SYNC;
DROP TABLE IF EXISTS DEDUP_DECISION_ITEM;
DROP TABLE IF EXISTS DEDUP_DECISION;
DROP TABLE IF EXISTS DEDUP_OVERRIDE;
DROP TABLE IF EXISTS DEDUP_REVIEW_CASE_MEMBER;
DROP TABLE IF EXISTS DEDUP_REVIEW_CASE;
DROP TABLE IF EXISTS DEDUP_RELATION;
DROP TABLE IF EXISTS DEDUP_PAGE_FEATURE;
DROP TABLE IF EXISTS DEDUP_FEATURE;
DROP TABLE IF EXISTS DEDUP_WORK;
DROP TABLE IF EXISTS DEDUP_LIBRARY_SETTINGS;

CREATE TABLE DEDUP_LIBRARY_SETTINGS
(
    LIBRARY_ID                 varchar  NOT NULL PRIMARY KEY,
    ENABLED                    boolean  NOT NULL DEFAULT false,
    PAUSED                     boolean  NOT NULL DEFAULT false,
    SCAN_INTERVAL              varchar  NOT NULL DEFAULT 'DAILY',
    BATCH_SIZE                 integer  NOT NULL DEFAULT 100 CHECK (BATCH_SIZE > 0),
    MAX_DURATION_SECONDS       integer  NOT NULL DEFAULT 300 CHECK (MAX_DURATION_SECONDS > 0),
    QUIET_PERIOD_SECONDS       integer  NOT NULL DEFAULT 180 CHECK (QUIET_PERIOD_SECONDS >= 0),
    COVER_CANDIDATE_DISTANCE  integer  NOT NULL DEFAULT 15 CHECK (COVER_CANDIDATE_DISTANCE BETWEEN 0 AND 256),
    COVER_TOP_K                integer  NOT NULL DEFAULT 20 CHECK (COVER_TOP_K > 0),
    CREATED_DATE               datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE
);

CREATE TABLE DEDUP_WORK
(
    ID                  varchar  NOT NULL PRIMARY KEY,
    LIBRARY_ID          varchar  NOT NULL,
    TYPE                varchar  NOT NULL,
    TARGET_KEY          varchar  NOT NULL DEFAULT '',
    STATE               varchar  NOT NULL DEFAULT 'WAITING',
    DESIRED_REVISION    int8     NOT NULL DEFAULT 1 CHECK (DESIRED_REVISION > 0),
    COMPLETED_REVISION  int8     NOT NULL DEFAULT 0 CHECK (COMPLETED_REVISION >= 0),
    NOT_BEFORE          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NEXT_RETRY_AT       datetime NULL,
    LEASE_OWNER         varchar  NULL,
    LEASE_TOKEN         varchar  NULL,
    LEASE_UNTIL         datetime NULL,
    ATTEMPT_COUNT       integer  NOT NULL DEFAULT 0 CHECK (ATTEMPT_COUNT >= 0),
    MAX_ATTEMPTS        integer  NOT NULL DEFAULT 8 CHECK (MAX_ATTEMPTS > 0),
    LAST_ERROR_CODE     varchar  NULL,
    LAST_ERROR          varchar  NULL,
    PRIORITY            integer  NOT NULL DEFAULT 0,
    CREATED_DATE        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_DATE      datetime NULL,
    UNIQUE (LIBRARY_ID, TYPE, TARGET_KEY),
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE,
    CHECK (STATE IN ('WAITING', 'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED_REVIEW', 'CANCELLED'))
);

CREATE INDEX IDX__DEDUP_WORK__CLAIM ON DEDUP_WORK (STATE, NOT_BEFORE, NEXT_RETRY_AT, PRIORITY, CREATED_DATE);
CREATE INDEX IDX__DEDUP_WORK__LEASE ON DEDUP_WORK (STATE, LEASE_UNTIL);

CREATE TABLE DEDUP_FEATURE
(
    BOOK_ID                     varchar  NOT NULL PRIMARY KEY,
    SERIES_ID                   varchar  NOT NULL,
    LIBRARY_ID                  varchar  NOT NULL,
    SOURCE_CONTENT_GENERATION   varchar  NOT NULL,
    SOURCE_COVER_GENERATION     varchar  NOT NULL DEFAULT '',
    SOURCE_METADATA_GENERATION  varchar  NOT NULL DEFAULT '',
    SERIES_SCOPE_REVISION       varchar  NOT NULL,
    FEATURE_SCHEMA_VERSION      integer  NOT NULL,
    COVER_STATE                 varchar  NOT NULL DEFAULT 'WAITING',
    PAGE_STATE                  varchar  NOT NULL DEFAULT 'WAITING',
    COVER_SOURCE                varchar  NULL,
    COVER_HASH                  blob     NULL,
    COVER_QUALITY               integer  NULL,
    PAGE_COUNT                  integer  NULL,
    ANALYZED_DATE               datetime NULL,
    LAST_MODIFIED_DATE          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID) ON DELETE CASCADE,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE
);

CREATE INDEX IDX__DEDUP_FEATURE__LIBRARY_COVER ON DEDUP_FEATURE (LIBRARY_ID, COVER_STATE, FEATURE_SCHEMA_VERSION);

CREATE TABLE DEDUP_PAGE_FEATURE
(
    BOOK_ID                    varchar NOT NULL,
    SOURCE_CONTENT_GENERATION  varchar NOT NULL,
    FEATURE_SCHEMA_VERSION     integer NOT NULL,
    PAGE_NUMBER                integer NOT NULL CHECK (PAGE_NUMBER > 0),
    EXACT_HASH                 varchar NULL,
    PERCEPTUAL_HASH            blob    NULL,
    QUALITY                    integer NULL,
    PRIMARY KEY (BOOK_ID, SOURCE_CONTENT_GENERATION, FEATURE_SCHEMA_VERSION, PAGE_NUMBER),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE
);

CREATE TABLE DEDUP_RELATION
(
    ID                            varchar  NOT NULL PRIMARY KEY,
    LIBRARY_ID                    varchar  NOT NULL,
    BOOK_LOW_ID                   varchar  NOT NULL,
    BOOK_HIGH_ID                  varchar  NOT NULL,
    LOW_CONTENT_GENERATION        varchar  NOT NULL,
    HIGH_CONTENT_GENERATION       varchar  NOT NULL,
    LOW_COVER_GENERATION          varchar  NOT NULL DEFAULT '',
    HIGH_COVER_GENERATION         varchar  NOT NULL DEFAULT '',
    LOW_METADATA_GENERATION       varchar  NOT NULL DEFAULT '',
    HIGH_METADATA_GENERATION      varchar  NOT NULL DEFAULT '',
    RELATION_TYPE                 varchar  NOT NULL,
    CONTAINED_BOOK_ID             varchar  NULL,
    CONTAINER_BOOK_ID             varchar  NULL,
    COVER_DISTANCE                integer  NULL,
    COVERAGE_LEFT                 real     NULL,
    COVERAGE_RIGHT                real     NULL,
    ORDER_CONSISTENCY             real     NULL,
    LONGEST_MATCHED_RUN           integer  NULL,
    UNMATCHED_PREFIX_COUNT        integer  NULL,
    UNMATCHED_SUFFIX_COUNT        integer  NULL,
    UNMATCHED_INTERNAL_COUNT      integer  NULL,
    CONFIDENCE                    real     NULL,
    EVIDENCE_JSON                 varchar  NOT NULL DEFAULT '{}',
    FEATURE_SCHEMA_VERSION        integer  NOT NULL,
    CLASSIFIER_RULE_VERSION       integer  NOT NULL,
    STATUS                        varchar  NOT NULL,
    CREATED_DATE                  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE            datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (BOOK_LOW_ID, BOOK_HIGH_ID),
    CHECK (BOOK_LOW_ID < BOOK_HIGH_ID),
    FOREIGN KEY (BOOK_LOW_ID) REFERENCES BOOK (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_HIGH_ID) REFERENCES BOOK (ID) ON DELETE CASCADE,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE
);

CREATE INDEX IDX__DEDUP_RELATION__LIBRARY_STATUS ON DEDUP_RELATION (LIBRARY_ID, STATUS, RELATION_TYPE);

CREATE TABLE DEDUP_GORSE_SYNC
(
    SERIES_ID           varchar  NOT NULL PRIMARY KEY,
    LIBRARY_ID          varchar  NOT NULL,
    DESIRED_HIDDEN      boolean  NOT NULL,
    STATE               varchar  NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT       integer  NOT NULL DEFAULT 0,
    NEXT_RETRY_AT       datetime NULL,
    LAST_ERROR          varchar  NULL,
    CREATED_DATE        datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_DATE      datetime NULL,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE,
    CHECK (STATE IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED_REVIEW'))
);

CREATE INDEX IDX__DEDUP_GORSE_SYNC__CLAIM ON DEDUP_GORSE_SYNC (STATE, NEXT_RETRY_AT, LAST_MODIFIED_DATE);

CREATE TABLE DEDUP_CLUSTER
(
    ID                    varchar  NOT NULL PRIMARY KEY,
    LIBRARY_ID            varchar  NOT NULL,
    REVISION              int8     NOT NULL DEFAULT 1 CHECK (REVISION > 0),
    STATUS                varchar  NOT NULL DEFAULT 'UNPROCESSED',
    REVIEWABLE            boolean  NOT NULL DEFAULT true,
    ANCHOR_BOOK_ID        varchar  NOT NULL,
    TOPOLOGY_FINGERPRINT  varchar  NOT NULL,
    EVIDENCE_FINGERPRINT  varchar  NOT NULL,
    STATE_FINGERPRINT     varchar  NOT NULL,
    PROCESSED_REVISION    int8     NULL,
    LAST_RESOLUTION_ID    varchar  NULL,
    REOPEN_REASON         varchar  NULL,
    SUPERSEDED_BY         varchar  NULL,
    CREATED_DATE          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_DATE        datetime NULL,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID) ON DELETE CASCADE,
    FOREIGN KEY (SUPERSEDED_BY) REFERENCES DEDUP_CLUSTER (ID),
    CHECK (STATUS IN ('UNPROCESSED', 'PROCESSING', 'PROCESSED', 'NEEDS_ATTENTION'))
);

CREATE INDEX IDX__DEDUP_CLUSTER__LIBRARY_STATUS ON DEDUP_CLUSTER (LIBRARY_ID, STATUS, LAST_MODIFIED_DATE);
CREATE INDEX IDX__DEDUP_CLUSTER__REVIEWABLE_STATUS ON DEDUP_CLUSTER (REVIEWABLE, STATUS);
CREATE INDEX IDX__DEDUP_CLUSTER__SUPERSEDED_BY ON DEDUP_CLUSTER (SUPERSEDED_BY);

CREATE TABLE DEDUP_CLUSTER_MEMBER
(
    CLUSTER_ID                 varchar  NOT NULL,
    BOOK_ID                    varchar  NOT NULL,
    PRESENT                    boolean  NOT NULL DEFAULT true,
    SOURCE_CONTENT_GENERATION  varchar  NOT NULL,
    SOURCE_COVER_GENERATION    varchar  NOT NULL,
    SOURCE_METADATA_GENERATION varchar  NOT NULL,
    SERIES_SCOPE_REVISION      varchar  NOT NULL,
    CREATED_DATE               datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE         datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CLUSTER_ID, BOOK_ID),
    FOREIGN KEY (CLUSTER_ID) REFERENCES DEDUP_CLUSTER (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE
);

CREATE INDEX IDX__DEDUP_CLUSTER_MEMBER__BOOK ON DEDUP_CLUSTER_MEMBER (BOOK_ID, PRESENT);

CREATE TABLE DEDUP_RESOLUTION
(
    ID                    varchar  NOT NULL PRIMARY KEY,
    CLUSTER_ID            varchar  NOT NULL,
    CLUSTER_REVISION      int8     NOT NULL,
    MODE                  varchar  NOT NULL,
    PLAN_REVISION         varchar  NOT NULL,
    PLAN_JSON             varchar  NOT NULL,
    EVIDENCE_JSON         varchar  NOT NULL,
    ELIGIBILITY_JSON      varchar  NOT NULL,
    RULE_VERSION          integer  NOT NULL,
    STATE                 varchar  NOT NULL DEFAULT 'PROCESSING',
    ACTOR_ID              varchar  NOT NULL,
    RESULT_JSON           varchar  NOT NULL DEFAULT '{}',
    LEASE_TOKEN           varchar  NOT NULL,
    LEASE_UNTIL           datetime NOT NULL,
    CREATED_DATE          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_DATE        datetime NULL,
    FOREIGN KEY (CLUSTER_ID) REFERENCES DEDUP_CLUSTER (ID) ON DELETE CASCADE,
    CHECK (MODE IN ('SUGGESTED', 'CUSTOM')),
    CHECK (STATE IN ('PROCESSING', 'PROCESSED', 'NEEDS_ATTENTION', 'PARTIALLY_COMPLETED'))
);

CREATE INDEX IDX__DEDUP_RESOLUTION__STATE ON DEDUP_RESOLUTION (STATE, LAST_MODIFIED_DATE);
CREATE INDEX IDX__DEDUP_RESOLUTION__CLUSTER ON DEDUP_RESOLUTION (CLUSTER_ID, CREATED_DATE);
CREATE INDEX IDX__DEDUP_RESOLUTION__LEASE ON DEDUP_RESOLUTION (STATE, LEASE_UNTIL);

CREATE TABLE DEDUP_RESOLUTION_MEMBER
(
    RESOLUTION_ID                    varchar  NOT NULL,
    BOOK_ID                          varchar  NOT NULL,
    SERIES_ID                        varchar  NOT NULL,
    LIBRARY_ID                       varchar  NOT NULL,
    ACTION                           varchar  NOT NULL,
    KEEPER_BOOK_ID                   varchar  NULL,
    TITLE_SNAPSHOT                   varchar  NOT NULL,
    PATH_SNAPSHOT                    varchar  NOT NULL,
    SOURCE_GENERATIONS_JSON          varchar  NOT NULL,
    LOCAL_STATE_SNAPSHOT_JSON        varchar  NOT NULL,
    DIRECT_RELATION_ID               varchar  NULL,
    DIRECT_RELATION_SNAPSHOT_JSON    varchar  NULL,
    EXPECTED_PATH                    varchar  NULL,
    EXPECTED_SIZE                    int8     NULL,
    EXPECTED_MTIME                   datetime NULL,
    EXPECTED_ARCHIVE_HASH            varchar  NULL,
    STATE                            varchar  NOT NULL DEFAULT 'PLANNED',
    RESULT_CODE                      varchar  NULL,
    RESULT_JSON                      varchar  NULL,
    LAST_ERROR                       varchar  NULL,
    CREATED_DATE                     datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE               datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOLUTION_ID, BOOK_ID),
    FOREIGN KEY (RESOLUTION_ID) REFERENCES DEDUP_RESOLUTION (ID) ON DELETE CASCADE,
    CHECK (ACTION IN ('KEEP', 'DELETE')),
    CHECK ((ACTION = 'KEEP' AND KEEPER_BOOK_ID IS NULL) OR (ACTION = 'DELETE' AND KEEPER_BOOK_ID IS NOT NULL)),
    CHECK ((ACTION = 'KEEP' AND DIRECT_RELATION_ID IS NULL) OR (ACTION = 'DELETE' AND DIRECT_RELATION_ID IS NOT NULL)),
    CHECK (STATE IN ('PLANNED', 'PREFLIGHTED', 'DELETED', 'KOMGA_SAVED', 'GORSE_CONFIRMED', 'COMPLETED', 'FAILED', 'CONFLICT'))
);

CREATE INDEX IDX__DEDUP_RESOLUTION_MEMBER__BOOK ON DEDUP_RESOLUTION_MEMBER (BOOK_ID, STATE);
