ALTER TABLE DEDUP_LIBRARY_SETTINGS ADD COLUMN LAST_BATCH_DATE datetime NULL;
ALTER TABLE DEDUP_LIBRARY_SETTINGS ADD COLUMN LAST_BATCH_BOOK_COUNT integer NOT NULL DEFAULT 0
    CHECK (LAST_BATCH_BOOK_COUNT >= 0);

-- V2 replaces the three library-wide scan work types with one Book-scoped work item.
-- Derived work is safe to discard: events and the DAO-level unscanned query repopulate it.
DELETE FROM DEDUP_WORK
WHERE TYPE IN ('RECONCILE_EXACT_DUPLICATES', 'COMPUTE_COVER', 'FIND_COVER_NEIGHBORS');

CREATE TABLE DEDUP_PAIR_DECISION
(
    BOOK_LOW_ID    varchar  NOT NULL,
    BOOK_HIGH_ID   varchar  NOT NULL,
    DECISION       varchar  NOT NULL,
    RESOLUTION_ID  varchar  NULL,
    ACTOR_ID       varchar  NOT NULL,
    CREATED_DATE   datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_LOW_ID, BOOK_HIGH_ID),
    CHECK (BOOK_LOW_ID < BOOK_HIGH_ID),
    CHECK (DECISION IN ('KEEP_BOTH')),
    FOREIGN KEY (BOOK_LOW_ID) REFERENCES BOOK (ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_HIGH_ID) REFERENCES BOOK (ID) ON DELETE CASCADE,
    FOREIGN KEY (RESOLUTION_ID) REFERENCES DEDUP_RESOLUTION (ID) ON DELETE SET NULL
);

CREATE INDEX IDX__DEDUP_PAIR_DECISION__RESOLUTION
    ON DEDUP_PAIR_DECISION (RESOLUTION_ID);

-- Preserve the intent of already processed clusters. Only survivor pairs with content
-- evidence are migrated, while cover-only and explicitly unrelated pairs are not suppressed.
INSERT OR IGNORE INTO DEDUP_PAIR_DECISION
    (BOOK_LOW_ID, BOOK_HIGH_ID, DECISION, RESOLUTION_ID, ACTOR_ID, CREATED_DATE)
SELECT ML.BOOK_ID,
       MH.BOOK_ID,
       'KEEP_BOTH',
       RES.ID,
       COALESCE(RES.ACTOR_ID, 'system:migration'),
       COALESCE(C.PROCESSED_DATE, C.LAST_MODIFIED_DATE, CURRENT_TIMESTAMP)
FROM DEDUP_CLUSTER C
JOIN DEDUP_CLUSTER_MEMBER ML
  ON ML.CLUSTER_ID = C.ID AND ML.PRESENT = true
JOIN DEDUP_CLUSTER_MEMBER MH
  ON MH.CLUSTER_ID = C.ID AND MH.PRESENT = true AND ML.BOOK_ID < MH.BOOK_ID
JOIN BOOK BL
  ON BL.ID = ML.BOOK_ID AND BL.DELETED_DATE IS NULL
JOIN BOOK BH
  ON BH.ID = MH.BOOK_ID AND BH.DELETED_DATE IS NULL
JOIN DEDUP_RELATION R
  ON R.BOOK_LOW_ID = ML.BOOK_ID AND R.BOOK_HIGH_ID = MH.BOOK_ID
LEFT JOIN DEDUP_RESOLUTION RES
  ON RES.ID = C.LAST_RESOLUTION_ID
WHERE C.STATUS = 'PROCESSED'
  AND R.RELATION_TYPE <> 'UNRELATED';

-- SQLite cannot remove CHECK clauses in place. Keep all legacy audit columns and
-- member states, while allowing new DELETE rows to omit keeper/direct relation data.
CREATE TABLE DEDUP_RESOLUTION_MEMBER_NEW
(
    RESOLUTION_ID                    varchar  NOT NULL,
    BOOK_ID                          varchar  NOT NULL,
    SERIES_ID                        varchar  NOT NULL,
    LIBRARY_ID                       varchar  NOT NULL,
    ACTION                           varchar  NOT NULL,
    KEEPER_BOOK_ID                   varchar  NULL,
    TITLE_SNAPSHOT                   varchar  NOT NULL,
    PATH_SNAPSHOT                    varchar  NOT NULL,
    SOURCE_GENERATIONS_JSON          varchar  NOT NULL,
    LOCAL_STATE_SNAPSHOT_JSON        varchar  NOT NULL,
    DIRECT_RELATION_ID               varchar  NULL,
    DIRECT_RELATION_SNAPSHOT_JSON    varchar  NULL,
    EXPECTED_PATH                    varchar  NULL,
    EXPECTED_SIZE                    int8     NULL,
    EXPECTED_MTIME                   datetime NULL,
    EXPECTED_ARCHIVE_HASH            varchar  NULL,
    STATE                            varchar  NOT NULL DEFAULT 'PLANNED',
    RESULT_CODE                      varchar  NULL,
    RESULT_JSON                      varchar  NULL,
    LAST_ERROR                       varchar  NULL,
    CREATED_DATE                     datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE               datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOLUTION_ID, BOOK_ID),
    FOREIGN KEY (RESOLUTION_ID) REFERENCES DEDUP_RESOLUTION (ID) ON DELETE CASCADE,
    CHECK (ACTION IN ('KEEP', 'DELETE')),
    CHECK (STATE IN ('PLANNED', 'PREFLIGHTED', 'DELETED', 'KOMGA_SAVED', 'GORSE_CONFIRMED', 'COMPLETED', 'FAILED', 'CONFLICT'))
);

INSERT INTO DEDUP_RESOLUTION_MEMBER_NEW
SELECT RESOLUTION_ID,
       BOOK_ID,
       SERIES_ID,
       LIBRARY_ID,
       ACTION,
       KEEPER_BOOK_ID,
       TITLE_SNAPSHOT,
       PATH_SNAPSHOT,
       SOURCE_GENERATIONS_JSON,
       LOCAL_STATE_SNAPSHOT_JSON,
       DIRECT_RELATION_ID,
       DIRECT_RELATION_SNAPSHOT_JSON,
       EXPECTED_PATH,
       EXPECTED_SIZE,
       EXPECTED_MTIME,
       EXPECTED_ARCHIVE_HASH,
       STATE,
       RESULT_CODE,
       RESULT_JSON,
       LAST_ERROR,
       CREATED_DATE,
       LAST_MODIFIED_DATE
FROM DEDUP_RESOLUTION_MEMBER;

DROP TABLE DEDUP_RESOLUTION_MEMBER;
ALTER TABLE DEDUP_RESOLUTION_MEMBER_NEW RENAME TO DEDUP_RESOLUTION_MEMBER;

CREATE INDEX IDX__DEDUP_RESOLUTION_MEMBER__BOOK
    ON DEDUP_RESOLUTION_MEMBER (BOOK_ID, STATE);
