ALTER TABLE DEDUP_FEATURE ADD COLUMN ARCHIVE_HASH varchar NULL;
ALTER TABLE DEDUP_FEATURE ADD COLUMN ARCHIVE_HASH_PATH varchar NULL;
ALTER TABLE DEDUP_FEATURE ADD COLUMN ARCHIVE_HASH_SIZE int8 NULL;
ALTER TABLE DEDUP_FEATURE ADD COLUMN ARCHIVE_HASH_SCHEMA_VERSION integer NULL;
ALTER TABLE DEDUP_FEATURE ADD COLUMN ARCHIVE_HASH_DATE datetime NULL;

ALTER TABLE DEDUP_CLUSTER ADD COLUMN MEMBER_COUNT integer NOT NULL DEFAULT 0;
ALTER TABLE DEDUP_CLUSTER ADD COLUMN VERIFIED_PAIR_COUNT integer NOT NULL DEFAULT 0;
ALTER TABLE DEDUP_CLUSTER ADD COLUMN TOTAL_PAIR_COUNT integer NOT NULL DEFAULT 0;
ALTER TABLE DEDUP_CLUSTER ADD COLUMN EVIDENCE_MATURITY varchar NOT NULL DEFAULT 'COVER_ONLY'
    CHECK (EVIDENCE_MATURITY IN ('COVER_ONLY', 'PARTIAL', 'COMPLETE'));

-- Rebind existing derived data to the mtime-free generation without reading remote archives.
UPDATE DEDUP_PAGE_FEATURE
SET SOURCE_CONTENT_GENERATION = 'dedup-v2:' || CAST((SELECT FILE_SIZE FROM BOOK WHERE BOOK.ID = DEDUP_PAGE_FEATURE.BOOK_ID) AS varchar) || ':UNHASHED';

UPDATE DEDUP_RELATION
SET LOW_CONTENT_GENERATION = 'dedup-v2:' || CAST((SELECT FILE_SIZE FROM BOOK WHERE BOOK.ID = DEDUP_RELATION.BOOK_LOW_ID) AS varchar) || ':UNHASHED',
    HIGH_CONTENT_GENERATION = 'dedup-v2:' || CAST((SELECT FILE_SIZE FROM BOOK WHERE BOOK.ID = DEDUP_RELATION.BOOK_HIGH_ID) AS varchar) || ':UNHASHED';

UPDATE DEDUP_CLUSTER_MEMBER
SET SOURCE_CONTENT_GENERATION = 'dedup-v2:' || CAST((SELECT FILE_SIZE FROM BOOK WHERE BOOK.ID = DEDUP_CLUSTER_MEMBER.BOOK_ID) AS varchar) || ':UNHASHED';

UPDATE DEDUP_FEATURE
SET SOURCE_CONTENT_GENERATION = 'dedup-v2:' || CAST((SELECT FILE_SIZE FROM BOOK WHERE BOOK.ID = DEDUP_FEATURE.BOOK_ID) AS varchar) || ':UNHASHED';

UPDATE DEDUP_CLUSTER
SET MEMBER_COUNT = (
        SELECT COUNT(*) FROM DEDUP_CLUSTER_MEMBER M
        WHERE M.CLUSTER_ID = DEDUP_CLUSTER.ID AND M.PRESENT = true
    );

UPDATE DEDUP_CLUSTER
SET TOTAL_PAIR_COUNT = MEMBER_COUNT * (MEMBER_COUNT - 1) / 2;

UPDATE DEDUP_CLUSTER
SET VERIFIED_PAIR_COUNT = (
        SELECT COUNT(*)
        FROM DEDUP_RELATION R
        JOIN DEDUP_CLUSTER_MEMBER ML
          ON ML.CLUSTER_ID = DEDUP_CLUSTER.ID AND ML.BOOK_ID = R.BOOK_LOW_ID AND ML.PRESENT = true
        JOIN DEDUP_CLUSTER_MEMBER MH
          ON MH.CLUSTER_ID = DEDUP_CLUSTER.ID AND MH.BOOK_ID = R.BOOK_HIGH_ID AND MH.PRESENT = true
        WHERE R.STATUS = 'VERIFIED'
          AND R.RELATION_TYPE <> 'VISUALLY_SIMILAR'
          AND R.LOW_CONTENT_GENERATION = ML.SOURCE_CONTENT_GENERATION
          AND R.HIGH_CONTENT_GENERATION = MH.SOURCE_CONTENT_GENERATION
    );

UPDATE DEDUP_CLUSTER
SET EVIDENCE_MATURITY = CASE
        WHEN VERIFIED_PAIR_COUNT = 0 THEN 'COVER_ONLY'
        WHEN VERIFIED_PAIR_COUNT >= TOTAL_PAIR_COUNT THEN 'COMPLETE'
        ELSE 'PARTIAL'
    END;

UPDATE DEDUP_CLUSTER
SET REVISION = REVISION + 1,
    STATUS = 'UNPROCESSED',
    PROCESSED_REVISION = NULL,
    REOPEN_REASON = 'IDENTITY_RULE_CHANGED',
    PROCESSED_DATE = NULL,
    LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHERE STATUS = 'PROCESSED';

CREATE INDEX IDX__DEDUP_CLUSTER__FILTER
    ON DEDUP_CLUSTER (REVIEWABLE, STATUS, EVIDENCE_MATURITY, LAST_MODIFIED_DATE DESC, ID);

-- SQLite CHECK constraints require a table rebuild to add the audit-only ABANDONED state.
CREATE TABLE DEDUP_RESOLUTION_NEW
(
    ID                    varchar  NOT NULL PRIMARY KEY,
    CLUSTER_ID            varchar  NOT NULL,
    CLUSTER_REVISION      int8     NOT NULL,
    MODE                  varchar  NOT NULL,
    PLAN_REVISION         varchar  NOT NULL,
    PLAN_JSON             varchar  NOT NULL,
    EVIDENCE_JSON         varchar  NOT NULL,
    ELIGIBILITY_JSON      varchar  NOT NULL,
    RULE_VERSION          integer  NOT NULL,
    STATE                 varchar  NOT NULL DEFAULT 'PROCESSING',
    ACTOR_ID              varchar  NOT NULL,
    RESULT_JSON           varchar  NOT NULL DEFAULT '{}',
    LEASE_TOKEN           varchar  NOT NULL,
    LEASE_UNTIL           datetime NOT NULL,
    CREATED_DATE          datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE    datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_DATE        datetime NULL,
    FOREIGN KEY (CLUSTER_ID) REFERENCES DEDUP_CLUSTER (ID) ON DELETE CASCADE,
    CHECK (MODE IN ('SUGGESTED', 'CUSTOM')),
    CHECK (STATE IN ('PROCESSING', 'PROCESSED', 'NEEDS_ATTENTION', 'PARTIALLY_COMPLETED', 'ABANDONED'))
);

INSERT INTO DEDUP_RESOLUTION_NEW
SELECT * FROM DEDUP_RESOLUTION;

CREATE TABLE DEDUP_RESOLUTION_MEMBER_BACKUP AS
SELECT * FROM DEDUP_RESOLUTION_MEMBER;

DROP TABLE DEDUP_RESOLUTION_MEMBER;
DROP TABLE DEDUP_RESOLUTION;
ALTER TABLE DEDUP_RESOLUTION_NEW RENAME TO DEDUP_RESOLUTION;

CREATE INDEX IDX__DEDUP_RESOLUTION__STATE ON DEDUP_RESOLUTION (STATE, LAST_MODIFIED_DATE);
CREATE INDEX IDX__DEDUP_RESOLUTION__CLUSTER ON DEDUP_RESOLUTION (CLUSTER_ID, CREATED_DATE);
CREATE INDEX IDX__DEDUP_RESOLUTION__LEASE ON DEDUP_RESOLUTION (STATE, LEASE_UNTIL);

CREATE TABLE DEDUP_RESOLUTION_MEMBER
(
    RESOLUTION_ID                    varchar  NOT NULL,
    BOOK_ID                          varchar  NOT NULL,
    SERIES_ID                        varchar  NOT NULL,
    LIBRARY_ID                       varchar  NOT NULL,
    ACTION                           varchar  NOT NULL,
    KEEPER_BOOK_ID                   varchar  NULL,
    TITLE_SNAPSHOT                   varchar  NOT NULL,
    PATH_SNAPSHOT                    varchar  NOT NULL,
    SOURCE_GENERATIONS_JSON          varchar  NOT NULL,
    LOCAL_STATE_SNAPSHOT_JSON        varchar  NOT NULL,
    DIRECT_RELATION_ID               varchar  NULL,
    DIRECT_RELATION_SNAPSHOT_JSON    varchar  NULL,
    EXPECTED_PATH                    varchar  NULL,
    EXPECTED_SIZE                    int8     NULL,
    EXPECTED_MTIME                   datetime NULL,
    EXPECTED_ARCHIVE_HASH            varchar  NULL,
    STATE                            varchar  NOT NULL DEFAULT 'PLANNED',
    RESULT_CODE                      varchar  NULL,
    RESULT_JSON                      varchar  NULL,
    LAST_ERROR                       varchar  NULL,
    CREATED_DATE                     datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE               datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOLUTION_ID, BOOK_ID),
    FOREIGN KEY (RESOLUTION_ID) REFERENCES DEDUP_RESOLUTION (ID) ON DELETE CASCADE,
    CHECK (ACTION IN ('KEEP', 'DELETE')),
    CHECK ((ACTION = 'KEEP' AND KEEPER_BOOK_ID IS NULL) OR (ACTION = 'DELETE' AND KEEPER_BOOK_ID IS NOT NULL)),
    CHECK ((ACTION = 'KEEP' AND DIRECT_RELATION_ID IS NULL) OR (ACTION = 'DELETE' AND DIRECT_RELATION_ID IS NOT NULL)),
    CHECK (STATE IN ('PLANNED', 'PREFLIGHTED', 'DELETED', 'KOMGA_SAVED', 'GORSE_CONFIRMED', 'COMPLETED', 'FAILED', 'CONFLICT'))
);

INSERT INTO DEDUP_RESOLUTION_MEMBER
SELECT * FROM DEDUP_RESOLUTION_MEMBER_BACKUP;

DROP TABLE DEDUP_RESOLUTION_MEMBER_BACKUP;
CREATE INDEX IDX__DEDUP_RESOLUTION_MEMBER__BOOK ON DEDUP_RESOLUTION_MEMBER (BOOK_ID, STATE);
