# ARM64 原生构建
labels:
  arch: arm64
when:
  - event: push
    branch: master
    evaluate: 'CI_REPO_OWNER == "maolei1024"'
steps:
  - name: gradle-build
    image: docker.nexus.ixuni.win/baseimage/java21-node20
    commands:
      - chmod +x ./gradlew
      - './gradlew :komga:ktlintCheck :komga:test :komga:prepareThymeLeaf :komga:bootJar --no-daemon'

  - name: build
    image: docker.io/woodpeckerci/plugin-docker-buildx:6.1.1@sha256:9a22c00b4952e405d11e66d29772edbeb1f7b24f27f71cda251ecb838e725e86
    settings:
      repo: docker.nexus.ixuni.win/komga
      registry: docker.nexus.ixuni.win
      tags: "${CI_PIPELINE_NUMBER}-arm64"
      platforms: linux/arm64
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password

  - name: notify-failure
    image: docker.nexus.ixuni.win/woodpecker-mlntfy:latest
    pull: true
    when:
      - status: [failure]
    settings:
      url: https://mlntfy.project.k3s.ixuni.win
      topic: mlNtfy
      status: failure
      priority: high
      tags: ci,failure,build,arm64
